spring.application.name=restaurant-app

# Ket noi co so du lieu H2 (chay tam tren Mac)
spring.datasource.url=jdbc:h2:mem:restaurantdb
spring.datasource.username=sa
spring.datasource.password=

# Tu dong tao bang tu code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
